myfirst/myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:articleID>/', views.detail, name='detail'),
    path('<int:articleID>/leave_comment/', views.leave_comment, name='leave_comment')
]

myfirst/myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
]

myfirst/myfirst/apps/articles/models.py
from django.db import models


class Article(models.Model):
    articleTitle = models.CharField('название статьи', max_length=200)
    articleText = models.TextField('текст статьи')
    pubDate = models.DateTimeField('дата публикации')

    def __str__(self):
        return self.articleTitle

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    authorName = models.CharField('имя автора', max_length=50)
    commentText = models.CharField('текст комментария', max_length=200)

    def __str__(self):
        return self.authorName

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

myfirst/myfirst/apps/articles/views.py
from django.shortcuts import render
from .models import Article, Comment
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
    listArticles = Article.objects.order_by('-pubDate')[:5]
    return render(request, 'articles/list.html', {"listArticles": listArticles})


def detail(request, articleID):
    try:
        a = Article.objects.get(id=articleID)
    except:
        raise Http404("Статья не найдена!")
    comments = a.comment_set.order_by('-id')[:10]
    return render(request, "articles/detail.html", {'article': a, "comments": comments})


def leave_comment(request, articleID):
    try:
        a = Article.objects.get(id=articleID)
    except:
        raise Http404("Статья не найдена!")

    a.comment_set.create(authorName=request.POST["name"], commentText=request.POST["text"])
    return HttpResponseRedirect(reverse("articles:detail", args=(a.id,)))

myfirst/myfirst/templates/articles/detail.html
{% extends 'base.html' %}

{%block title%}{{article.articleTitle}}{% endblock %}


{% block content %}

<h2>{{article.articleTitle}}</h2>
<p>{{article.articleText}}</p>
<em>{{article.pubDate}}</em>
<hr>
    {% if comments %}
        {% for c in comments%}
        <p>
            <strong>{{c.authorName}}</strong>
            <p>{{c.commentText}}</p>
        </p>
        {% endfor %}
    {% else %}
        Комментарии не найдены
    {% endif %}
<hr>


<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
    {% csrf_token %}
    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>
    <button type="submit">Оставить комментарий</button>
</form>
{% endblock %}

myfirst/myfirst/templates/articles/list.html
{% extends 'base.html' %}

{%block title%}Последние статьи {% endblock %}



{% block content %}

    {% if listArticles %}
        {% for a in listArticles%}
        <a href={% url 'articles:detail' a.id%}>{{a.articleTitle}}</a>
        {% endfor %}
    {% else %}
        Статьи не найдены
    {% endif %}

{% endblock %}

myfirst/myfirst/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Сайт{% endblock %}</title>
</head>
<body>
        {% block content %}{% endblock %}
</body>
</html>